### ISSUE TITLE
Birthday Function

### ISSUE THREAD

**Issue by Bearmun** [Tacokeet/WTFP-Discord-bot#1]
Oh Holy Taco Jesus. Hereby I would like to request a feature in which we, peasants, can add, list, remove birthdays to/from the bot. It would be nice too also congratulate people automatically via the bot. 🥳

Eigenlijk wordt het gewoon een verkapte agenda. :)

**Comment by Tacokeet** [comment]
Please label your issues next 😊

**Comment by Tacokeet** [comment]
Added in commit ac9f5804760650627dd5aa36c2335a1f9c3b05ec. Need to add new sounds tho
